### ISSUE TITLE
Bug: compile error on typescript + vue3 project

### ISSUE THREAD

**Issue by m0a** [mib200/vue-gtm#111]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v3.2.0        |
| Vue    | v3.0.0        |
|TypeScript| v3.9.3 |
| Node   | v12.18.2        |
| OS     | mac |

## Input

error sample repo is https://github.com/m0a-mystudy/vuegtm-tserror-sample

## Output or Error

```bash
ERROR in src/components/HelloWorld.vue:42:15
TS2339: Property 'trackView' does not exist on type 'Plugin_2'.
  Property 'trackView' does not exist on type 'PluginInstallFunction & { install?: PluginInstallFunction | undefined; }'.
    40 |   },
    41 |   mounted(){
  > 42 |     this.$gtm.trackView("MyScreenName", "currentpath");
       |               ^^^^^^^^^
    43 |   }
    44 | });
    45 | </script>
```

**Comment by Shinigami92** [comment]
Thanks for the report :+1:  
Indeed it was a wrong type definition :sweat:  
Please try `3.2.1` and report back to me if everything works
