### ISSUE TITLE
Page view/router changes are not reported to Google Analytics

### ISSUE THREAD

**Issue by tcorcor1** [mib200/vue-gtm#113]
First, thank you for making and sharing this. 

Unfortunately, I just discovered the plugin is not reporting router changes/page changes to Google Analytics. I discovered this in upgrading an app to Vue 3 (plugin v. 3.1.1).  

```javascript

app.use(createGtm({
    id: 'GTM-000000', 
    defer: false, 
    compatibility: false,
    enabled: true,
    debug: false,
    loadScript: true,
    vueRouter: router,
    trackOnNextTick: false,
}));

````

I went back to a Vue 2 app using plugin v. 2.3.2 and confirmed this issue exists there as well (same implementation as above). 

This plugin works on the first page load or a hard-refresh but when navigating around 2nd, 3rd, 4th page view are not tracked. I have turned on debugging and verified that the page-views "appear" to be tracked but I tested in Google Analytics hitting a secret page and confirmed a lot of page views are not coming back.

My implementation follows your documentation  using the options API in both tests

```javascript

  mounted() {
    this.$gtm.trackView("MyScreenName", "currentpath");
  },

```

Do you have any suggestions / recommendations of things to try to resolve this issue?

Thanks in advance

**Comment by Shinigami92** [comment]
Sorry that I need to tell you that I only took over this repository to at least support TypeScript and Vue 3 support.
So I'm not a user of Google Analytics myself and can only do my best without knowing it directly.

The plugins implementation is the same in 3.1.1 and 3.1.1-vue2, only how it will be registered to Vue 2 or 3 + the TS definitions are different. That said, you shouldn't need to extra call `trackView` to see navigation changes. `vueRouter: router` should keep this in sync automatically and `trackView` is just for extra stuff.

I get multiple requests about Google Analytics (GA) instead of Google Tag Manager (GTM). These seems to be similar but injects different scripts.
My plugin injects [`https://www.googletagmanager.com/gtm.js`](https://github.com/mib200/vue-gtm/blob/master/src/utils.ts#L48)
Other plugins inject [`https://www.google-analytics.com`](https://github.com/MatteoGabriele/vue-analytics/blob/master/src/bootstrap.js#L25)

I don't have enough knowledge myself about the difference but at least I hope I gave you some hints to lead you in the right direction.
If something of this helped you out, please let me know so I can maybe extend some points to the README.

**Comment by tcorcor1** [comment]
Thanks for the response. 

Unfortunately, I have confirmed in both versions passing the router did not result in any tracking beyond the initial page load. 

I decided to create my own component for GTM and push a custom event to the dataLayer via navigation guards.

**Comment by Shinigami92** [comment]
So basically the same thing that this plugin does within the `trackView` function?

https://github.com/mib200/vue-gtm/blob/2be0c66fd500a799035c8eadc56c71d2d4fe8268/src/plugin.ts#L79-L89

Did you see the log `Dispatching TrackView` at anytime?
I'm a little bit afraid of this `inBrowser` variable. It's older then my maintenance-takeover.
And I don't know why this check exists at all.

Can you give me your code of `dataLayer` and it's passed object (maybe censor some data)? Hopefully I can improve this plugin and fix it not only for you but for all users.

**Comment by tcorcor1** [comment]
Yes, I did see it dropping page view logs to the console. Were you able to recreate the issue? 

My implementation is incredibly simple, below is my navigation guard:

````javascript
router.afterEach(() => {
    if (window.dataLayer) {
        window.dataLayer.push({event: 'pageview'});
    }
});
````

I bind that event to my Universal Analytics tag and it works great. I tried to see if I could trigger the native/oob Page View in the same way but couldn't figure out the correct params to pass just yet.

**Comment by Shinigami92** [comment]
Thank you, that are good insights for me

So in our plugin the `afterEach` function is called here
https://github.com/mib200/vue-gtm/blob/2be0c66fd500a799035c8eadc56c71d2d4fe8268/src/index.ts#L81-L113

This calls the `trackView` function with potential additional event data, **but** the three properties `event`, `content-name` and `content-view-name` are specially overwritten by our plugin.
https://github.com/mib200/vue-gtm/blob/2be0c66fd500a799035c8eadc56c71d2d4fe8268/src/plugin.ts#L86-L88

Sadly I don't know why this is implemented so and what it would have an effect permitting users to use any event they want.
So it's hard-coded to `event: content-view`! But you are using `pageview` :thinking: 

Maybe I will restructure some parts of this plugin in the next few days (with help from your given code).

---

Please let me know if you have injected 
1. `https://www.googletagmanager.com/gtm.js` (https://developers.google.com/tag-manager/quickstart)
2. `https://www.google-analytics.com/analytics.js` (https://developers.google.com/analytics/devguides/collection/analyticsjs)
3. both of 1 (gtm) and 2 (ga)

---

According to this [guide](https://developers.google.com/tag-manager/devguide), the event parameter can be any given value?! Am I correct?

![image](https://user-images.githubusercontent.com/7195563/104954939-98b17f80-59c9-11eb-816d-b4733f042835.png)

Yeah I'm not a analytic manager but just a developer :sweat_smile: 
Thanks for any kind of information, this can only improve this plugin :+1:

**Comment by tcorcor1** [comment]
Of course, no problem. 

I am using gtm.js and yes the event name could be whatever. I just picked 'pageview' for my test.

**Comment by Shinigami92** [comment]
_Just for documentation purposes_: https://github.com/mib200/vue-gtm/commit/f99a60a9b8272a3bbb76e1b73ea45228cfff0952#diff-d6f975ceab5e8c813a5cc2627408ad9366bf607e4fe314dc1eab96b1eb450140R6

Seems the `inBrowser` check was introduced for server-side rendering :thinking:  
At least I should make this clear within the code with JSDoc + a logging output

**Comment by Abdulrahmanh995** [comment]
@Shinigami92 What about allowing the user to override the event name?
So the default value will be `content-view` and the user can override it with any already defined name that he used previously in existing projects

**Comment by Abdulrahmanh995** [comment]
@tcorcor1 Did you define a custom event in `GTM` dashboard with an event called `content-view`?
You have to create a custom event, not the default provided by `GTM` in case of SPA apps.

**Comment by Shinigami92** [comment]
> @Shinigami92 What about allowing the user to override the event name?
> So the default value will be `content-view` and the user can override it with any already defined name that he used previously in existing projects

Yeah that was my idea, but I'm currently not sure why this was designed this way and if it was intended or not.
Also there is a `trackEvent` function aside the `trackView` function! And there you can pass a custom event name if wanted, but also some other properties are _forced_ to be passed.

I personally don't know what both these functions are for in special. Sadly I don't find code-documentation about that.
I will explore the google developer guides the next days to get more information about that and maybe change it so users can override the default event passed to `trackView`.

I definitely also need to add JSDoc to these both function!

_As you can see, I started to work heavily today on the project and introduced jest-tests + linting_ :smiley:

**Comment by Shinigami92** [comment]
@tcorcor1 @Abdulrahmanh95 Just one thing I currently thought about...
This plugin adds the gtm-script and theoretically after everything is configured you can also manually call the following where ever you want instead of `trackView`/`trackEvent`
```js
if (this.$gtm.enabled()) {
  window.dataLayer.push({
    event: "myCustomEvent",
    // ...
  });
}
```

I'm currently in a process of thinking about to completely move this repo to somewhere (e.g. my own account) so I can better manage it
That's why I currently don't change the API of this plugin
Also I want to add many more tests before breaking too much, and this will maybe take one or two weekends
So just be patient :slightly_smiling_face:

**Comment by Shinigami92** [comment]
Added it to the README.md https://github.com/mib200/vue-gtm/commit/3f0a3033a800b7e154ccfe8c7560074b2818c4cc#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R167-R176

**Comment by Shinigami92** [comment]
Oh I found this: https://github.com/mib200/vue-gtm/issues/14#issuecomment-484158110

Did you try that? Also the README says this: 
https://github.com/mib200/vue-gtm/blob/3f0a3033a800b7e154ccfe8c7560074b2818c4cc/README.md#L119

**Comment by simplenotezy** [comment]
Pretty sure we track pageviews, but that is a setting that you need to enable in GTM as told by @Shinigami92

**Comment by simplenotezy** [comment]
@Shinigami92 Is 

> Oh I found this: [#14 (comment)](https://github.com/mib200/vue-gtm/issues/14#issuecomment-484158110)
> 
> Did you try that? Also the README says this:
> https://github.com/mib200/vue-gtm/blob/3f0a3033a800b7e154ccfe8c7560074b2818c4cc/README.md#L119

@Shinigami92 Actually, upon hours of debugging I am now in doubt. Is it required to enabkle "History Change Trigger" in GTM if you enable `trackOnNextTick` (i.e. setting value to `true`)?

**Comment by Shinigami92** [comment]
Uh I'm absolutely not sure :slightly_frowning_face: 
Sorry but this plugin was written by @mib200 and not me directly
I took it over but some mechanics like this I don't know what they do
I also have no knowledge about GTM directly :slightly_frowning_face: so I even don't know what `"History Change Trigger"` is

**Comment by Shinigami92** [comment]
If there are any new feature requests or any other issues, please feel free to request them in the new repo at https://github.com/gtm-support/vue-gtm or https://github.com/gtm-support/core
