### ISSUE TITLE
Support for Nonce

### ISSUE THREAD

**Issue by thinkflo** [mib200/vue-gtm#116]
## Request / Idea
Looking at the Vue-GTM plugin, there does not appear to be support for the Nonce attribute for usage with CSP.  This would be a very useful feature to have.
...

## Additional Context
https://developers.google.com/tag-manager/web/csp
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script
...

**Comment by Shinigami92** [comment]
@thinkflo Is there a reason why you closed this already? Is there a way for doing that? Do you just don't need it anymore? Other reasons?

**Comment by mohdhallal** [comment]
+1

**Comment by Shinigami92** [comment]
@mohdhallal I don’t understand your +1?!
Should I reopen this issue? If so: are you willing to create a PR for that?

**Comment by mohdhallal** [comment]
hello @Shinigami92 ! The +1 means that I faced this issue (trying to add a nonce) but failed to do so using this plugin and that I support a fix.

The change should be adding an extra option to the plugin and appending an attribute to the script tag https://github.com/mib200/vue-gtm/blob/master/src/utils.ts#L36 ?
