### ISSUE TITLE
Bug: Vue Router required by Vue GTM when its not even passed into the options

### ISSUE THREAD

**Issue by mara-schulke** [mib200/vue-gtm#122]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v3.4.1        |
| Vue    | v3.0.0       |
| Node   | v14.14.0        |
| OS     | linux & mac |

## Input

```js
	app.use(createGtm({
		id: 'GTM-FOO',
		defer: true,
		enabled: false,
		debug: process.env.NODE_ENV === 'development',
		loadScript: true,
		trackOnNextTick: false
	}));
```

## Output or Error

while building for production with webpack:

```bash
    ERROR in ../node_modules/vue-gtm/dist/index.js
    Module not found: Error: Can't resolve 'vue-router' in '/Users/foo-user/workspace/bar-project/node_modules/vue-gtm/dist'
     @ ../node_modules/vue-gtm/dist/index.js 162:85-106
     @ ./js/main.js
```

## Expected Output

No error.

## Additional Context

I am using vue-gtm in multipage project where vue-router isnt needed, but vue gtm still complains that vue-router int installed when building for production. I think it might relate to the fact that you use the `import('vue-router')` statement in your code (https://github.com/mib200/vue-gtm/blob/0a3691bc53b77d1e02de4040bec177346dc2f990/src/index.ts#L101).

I dont know how to fix this behavior, the last working version in my env is 3.1.1. Maybe specificing vue router as peer dep could help?

**Comment by Shinigami92** [comment]
Mh yes, I had [rebuilt](https://github.com/mib200/vue-gtm/commit/007608bfbdb68658d130b74b3802df1779d4fa5e#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R103) that to dynamically import it if necessary  
But I think webpack only sees the `import`, but doesn't know that this is in an if statement

Need to find a better strategy
Maybe I need to fallback to `require` :slightly_frowning_face:

**Comment by Shinigami92** [comment]
https://github.com/mib200/vue-gtm/blob/007608bfbdb68658d130b74b3802df1779d4fa5e/src/index.ts#L103

**Comment by Shinigami92** [comment]
Oops, wrong button :smile:

**Comment by Shinigami92** [comment]
Specifying it in `peerDependencies` would mean that the developer needs to add it to they dependencies, doesn't it?

**Comment by Shinigami92** [comment]
Okay, the emitted `index.js` already uses `require` instead of `import`
So my current build already transpiles it to `require`

**Comment by Shinigami92** [comment]
@schulke-214 Could you try this solution https://stackoverflow.com/a/58701883/6897682 for me?
Just interested if this helps :thinking:

**Comment by Shinigami92** [comment]
Okay I just worked around 2h on this problem for now...
Currently the best **workaround** seems to be to add `vue-router` to your `devDependencies`.

I'm now in contact with the Vite Discord and try to find a well suited solution so I have types and consumers don't have problems with the optional dependency.

**Comment by Shinigami92** [comment]
I created a [3.4.2-issue-122.1](https://www.npmjs.com/package/vue-gtm/v/3.4.2-issue-122.1)
Could you try it?

---

I'm not really satisfied with the result, because I use `optionalDependencies`. So `vue-router` will get downloaded AND also I think bundled via `webpack`/`vite` regardless if it is needed or not. And this makes the whole purpose of _optional_ worthless :confused:  

---

I'm thinking about to provide multiple bundles like `esm`, `amd` (/`umd`) and `cjs` via `rollup`.

**Cons:**
This would increase the package-size

**Pros:**
I think it may potentially solve the optional dependency for some configurations
It may produce a bit smaller bundle-size for the respective bundled frontend itself (less size for the browser)

**Comment by mara-schulke** [comment]
Hi! Sorry, yes i'll take a look at this later okay? Thanks for working on this so quickly!

**Comment by Shinigami92** [comment]
Note to me: Yes it gets bundled into the respective frontend :slightly_frowning_face: 

![image](https://user-images.githubusercontent.com/7195563/110603097-f15df700-8186-11eb-8f03-852b3c8a0ed3.png)

**Comment by mara-schulke** [comment]
Ah i see, same behavior in my project

**Comment by mara-schulke** [comment]
I mean that would uglify the api a little bit but i'd be perfectly fine with importing another build which doesnt require vue-router

Like `vue-gtm/slim` or whatever you want to name it, for pages without vue-router

I think the default case is to use it in vue based apps where you definetly have access to vue router

**Comment by mara-schulke** [comment]
https://github.com/mib200/vue-gtm/issues/122#issuecomment-793923232

Having this in my webpack config actually works:

```
    externals: {
        'vue-router': 'require("vue-router")'
    }
```

but tbh i find it a bit annoying to manually do that in my webpack config to work with a 3rd party package

**Comment by mara-schulke** [comment]
> Specifying it in `peerDependencies` would mean that the developer needs to add it to they dependencies, doesn't it?

ah yes you're right ^^ i didnt knew optional dependencies existed 🙂

**Comment by Shinigami92** [comment]
I also thought about something like `vue-gtm/slim`, but in the end it would be the same as the manual `webpack` configuration
Also I already have two versions to build, one for Vue 3 and one for Vue 2
So then it would theoretically be 4 versions :confused: 

I will think about this a bit more
In the meanwhile, you can use the `3.4.2-issue-122.1` as it is currently the master branch only with this fix

**Comment by Shinigami92** [comment]
Hi, sorry for letting waiting you so long, but I was working in other repos
So for now I don't see a better way then just using the `optionalDependencies` :slightly_frowning_face:  
I think I will create a release in some minutes :shrug:
