### ISSUE TITLE
Bug: refers to a value

### ISSUE THREAD

**Issue by hughes5135** [mib200/vue-gtm#125]
![image](https://user-images.githubusercontent.com/24431909/114513604-f07c2180-9c6c-11eb-9ff9-1905974f59f1.png)

**Comment by Shinigami92** [comment]
Could you create a reproducible repo and steps how to reproduce the issue?

From the first look it seems that it is not related to vue-gtm itself but an issue with html-webpack-plugin 🤔

**Comment by hughes5135** [comment]
在项目根目录的 tsconfig.json 里的 "compilerOptions" 对象中增加："lib": ["es5", "es2015.promise"]

**Comment by Shinigami92** [comment]
If you have any further issues, please open them at https://github.com/gtm-support/vue-gtm or https://github.com/gtm-support/core
