### ISSUE TITLE
Support to load the script in head tag instead of body.

### ISSUE THREAD

**Issue by thomsonsebastian** [mib200/vue-gtm#130]
I see the script is loaded in the body. 
Could we also have an option to load the script in head tag instead of body tag

**Comment by Shinigami92** [comment]
Please recreate the request in https://github.com/gtm-support/core/issues/new?template=feature-request.md&title=Support%20to%20load%20the%20script%20in%20head%20tag%20instead%20of%20body

**Comment by devmade** [comment]
Any updates regarding this issue? 
Where can I find the follow up?

**Comment by Shinigami92** [comment]
@devmade https://github.com/gtm-support/core/issues/55
