### ISSUE TITLE
Is auto tracking for vue router working?

### ISSUE THREAD

**Issue by dbeja** [mib200/vue-gtm#14]
Hi,

I've added vue-gmt and added the following config:
```
Vue.use(VueGtm, {
	debug: false,
	vueRouter: router
});
```
Also have google tag manager tags in the right place and I'm getting hits on Google Analytics.
But only when I refresh the page, if I go to other vue router links they are not tracked on GA.

**Comment by mib200** [comment]
Yes. We are using it in production and every page view is getting tracked. And I know 2 other companies who are using that in production and its working.

Are you sure you have configured everything correctly?

**Comment by dodotdot** [comment]
hi @mib200 i see in router we send the event using this
dataLayer.push({
				'event': 'content-view',
				'content-name': path
			})
how about if i want to add more custom attribute inside those dataLayer, for example:
typePage: 'about-us'

dataLayer.push({
				'event': 'content-view',
				'content-name': path,
                                typePage: 'about-us'
			})

**Comment by mib200** [comment]
you can do that... anything extra you send is automatically added to dataLayer push by destructuring that. Did you try the above code?

**Comment by jasdf2351** [comment]
Hi @mib200 great library, thank you for your hard work, however I'm seeing the same @dbeja . I'm using Vue 2.5.15, vue-router ^3.0.1, vue-gtm 1.0.2.

I've not yet published the container, but using preview mode in GTM and refreshing the browser is working as I can see the track, but when I nav to subsequent pages, with debug mode on it's logging to the console but it's not sending the data to GTM/GA.

When I refresh, the GTM debug panel shows the tag fired on 1. Page View, but subsequent content-views, it's not triggered.

I've got a router.beforeEach bit of code, so I also plumbed in a Vue.gtm.trackView(to.path, to.path) to this, it's firing off a console.log like the library code does, but again doesn't trigger a ping in GA.

Any ideas?

**Comment by jasdf2351** [comment]
Figured it out:
@dbeja see:
https://www.analyticsmania.com/post/single-page-web-app-with-google-tag-manager/

**Comment by mib200** [comment]
great! Most of the errors reported here are errors in GTM config etc. Please review them once. We are some others are already using it in production.

**Comment by zoe-edwards** [comment]
For me it was “History Change Trigger” from that article!

**Comment by murilobd** [comment]
I think I have this issue too! When I change the page using the router, is it expected to see some request to google analytics?
