### ISSUE TITLE
Remove vue-ua from documentation

### ISSUE THREAD

**Issue by danielgranat** [mib200/vue-gtm#15]
The documentation has a reference to vue-ua:

> Configuration
> npm install vue-gtm -S or yarn add vue-ua if you use Yarn package manager

Shouldn't it be vue-gtm?
"... yarn add **vue-gtm** if ..."

**Comment by mib200** [comment]
Ohh. Yes. Thanks for pointing out.



Regards
Manish Kumar
________________________________
