### ISSUE TITLE
'trackEvent' of undefined

### ISSUE THREAD

**Issue by vAhyThe** [mib200/vue-gtm#18]
Hi i dont know why this not work any clue ?? thx

```
router.afterEach((to, from) => {
  this.$gtm.trackEvent({
    event: null, // Event type [default = 'interaction'] (Optional)
    category: 'Calculator',
    action: 'click',
    label: 'Home page SIP calculator',
    value: 5000,
    noninteraction: false // Optional
  });
})

export default router
 ```

**Comment by fapspirit** [comment]
@vAhyThe Hello! You referencing to `this` in `afterEach` router callback. The example in the readme assumes that this is called from the component. In this callback, you need to call it from Vue itself, like `Vue.gtm.trackEvent()`.

**Comment by vAhyThe** [comment]
@fapspirit  i see thx
