### ISSUE TITLE
Auto Tracking in "history" router's mode

### ISSUE THREAD

**Issue by jonasrdm** [mib200/vue-gtm#19]
Hello!
It seems to me that the auto tracking does not work when vue-router's history mode is on.
I this expected? Am i'm doing something wrong?

**Comment by jonasrdm** [comment]
Actually It **does** work. 
I've figured out that it was another issue on my code. I'm closing the issue

**Comment by daanhaitsma** [comment]
I'm running into the same problem. Can you please tell me what the issue with your code was? Maybe the same thing will help with my code.
