### ISSUE TITLE
Cookies being set when enabled set to false

### ISSUE THREAD

**Issue by jacobnijgh** [mib200/vue-gtm#24]
_GA cookies are still being set, when enabled is set to false:

```javascript
// Init Google GTM
Vue.use(VueGtm, {
    enabled: false, // until we have a cookie allowed
    debug: false, // @todo we need config.json for this
    vueRouter: router,
});
```

Is this supposed to happen?

**Comment by mib200** [comment]
No its not supposed to happen. I'll take a look into this. Enabled false should disable the plugin.

Although, GTM itself might put some cookies. This plugin stops tracking the URL changes etc., but has no control over what cookies are set by GTM etc.

**Comment by dw33n** [comment]
@jacobnijgh I found out the same, as @mib200 says disabling the plugin will prevent it from tracking the URL changes. 

Using a cookie-check I look for an cookie that tells me the user has been shown and/or accepted (in this case) our gdpr-consent cookie, optionally including analytics being pushed by GTM.
- Doesn't exist? Show user the consent form. 
- Exists? Functional cookies are set AND if analytics is allowed `dataLayer.push({'event': 'consent-given'});` to a custom-event in GTM which then trigger the tags which themselves might set cookies as well. 

Hope this helps.
