### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by murilobd** [mib200/vue-gtm#28]
I am getting this error message:
```ReferenceError: jQuery is not defined```
and it's pointing to GoogleTagManager. Would be nice if this lib attach async the jQuery library and then start doing to GTM things.

**Comment by mib200** [comment]
jQuery is not required by GTM. I am using it in my project which doesn't have jQuery and it works fine. Can you please try again?

**Comment by murilobd** [comment]
Yeah! It was something wrong in my settings here that was requesting jQuery! Sorry for that!

**Comment by dukhevych** [comment]
Still have this issue, not sure what settings should be there to avoid it.

@murilobd can you assist?

**Comment by murilobd** [comment]
@Landen13 as far as I remember, it was something else from my project that was outputting that `jQuery is not defined` error. Nothing related to vue-gtm, actually.
Do a simple test and try it on an empty project and see if you get that error
