### ISSUE TITLE
Support for use inside an electron app

### ISSUE THREAD

**Issue by dorian-coygo** [mib200/vue-gtm#29]
Hi,

Any chance this could be adapted to be used inside an electron app? I know electron uses the `file://` protocol, but maybe there is a workaround that can be done inside this package?

Link to the electron issue that provides alternatives:
https://github.com/electron/electron/issues/8691

Thoughts?

**Comment by Sylk** [comment]
Have you tried to use it in an electron app @dorian-coygo?

**Comment by dorian-coygo** [comment]
Yes and it didn't work :/. We ended up going the GA analytics route instead

**Comment by mib200** [comment]
I'll take a look into this.

**Comment by Shinigami92** [comment]
I moved the repo to https://github.com/gtm-support/vue-gtm | https://github.com/gtm-support/core

Feel free to reopen an feature request there and I can try my best
But also a minimal reproduction repo would be welcome then :slightly_smiling_face:
