### ISSUE TITLE
Set the userId

### ISSUE THREAD

**Issue by LiamKlyneker** [mib200/vue-gtm#30]
How can I set the userId? with **this.$gtm**? dincamically(?), thanks! :)

**Comment by razbakov** [comment]
I had this problem too.

You need to add dataLayer variable. 

```
dataLayer.push({userId: userId})
```

I created [simplified version of this library](https://github.com/razbakov/vue-gtm-gtag/blob/master/index.js) that just creates `this.$gtag` (same as `gtag` in GTM documentation). So I was able to add dataLayer variables:

```
        this.$gtag({
          userId: user.uid
        });
```

and then use them in GTM.

After [my struggling with GTM](https://dev.to/razbakov/gtm-vs-gtag-1em7) I am thinking now to switch to [vue-gtag](https://github.com/MatteoGabriele/vue-gtag) and track events directly to  Google Analytics.

**Comment by Shinigami92** [comment]
Not quite sure if maybe https://github.com/mib200/vue-gtm/commit/7d835b40984b5cacde07457b622314971453d28a fixed it for you  
But also there seems to exist a workaround  
@LiamKlyneker Will close this for now, feel free to reopen or open a new issue

**Comment by selvinkuik** [comment]
Does the stated workaround work in the Vue 2 version, 3.0.0-vue2?
