### ISSUE TITLE
Fetch GTM id via Ajax

### ISSUE THREAD

**Issue by mikaelkarlsson-se** [mib200/vue-gtm#31]
Hi!
First of all, thanks for a great plugin!

I have a feature request about fetching the GTM id via Ajax (it doesn't seem to be possible at the moment?). I would like it to work as in [vue-analytics](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/installation.md#use-functions-orand-promises) where you can do an Ajax call when defining the id, would that be possible to implement? :)

**Comment by mib200** [comment]
I am unable to get the purpose of Ajax call to fetch GTM Id. Don't we know the ID already?

**Comment by mikaelkarlsson-se** [comment]
@mib200 In my case, the ID is defined in a CMS so I need to get it from there. Would be a quite common use case I think?
It's of course possible to do this in some other ways, but I think that how vue-analytics works is simple and nice.

**Comment by mib200** [comment]
@mikaelkarlsson-se you can load the ajax request first and after the response, init the Vue-GTM plugin. I have done it that way myself.
