### ISSUE TITLE
Id not being being assigned

### ISSUE THREAD

**Issue by SylarRuby** [mib200/vue-gtm#37]
As per docs:

```
Vue.use(VueGtm), {
  id: 'GTM-12345', // Your GTM ID
  enabled: true, // defaults to true. Plugin can be disabled by setting this to false for Ex: enabled: !!GDPR_Cookie (optional)
  debug: true, // Whether or not display console logs debugs (optional)
  vueRouter: router, // Pass the router instance to automatically sync with router (optional)
  ignoredViews: ['homepage'] // If router, you can exclude some routes name (case insensitive) (optional)
};
```

My browser log showing

`GET https://www.googletagmanager.com/gtm.js?id=undefined net::ERR_ABORTED 404`

Am I missing something?

**Comment by mib200** [comment]
Can you please try again? I am not having this error.

**Comment by avxkim** [comment]
same here, seems like googletagmanager.com is not working, throws 404

**Comment by MartinGerritsen** [comment]
I have the same issue with 2.0, when I went back to 1.0.3 it worked but events don't show up in the Tag Assistant

**Comment by oceangravity** [comment]
Guys you need to publish your Workspace in GTM

**Comment by mib200** [comment]
Can't reproduce. Please re-open if issue persists.
