### ISSUE TITLE
Where can I put the tacking id?

### ISSUE THREAD

**Issue by gbgelado** [mib200/vue-gtm#4]

**Comment by gbgelado** [comment]
On vue-analytics I can send my trackingId 

```javascript
Vue.use(VueAnalytics, {
  appName: '<app_name>', // Mandatory
  appVersion: '<app_version>', // Mandatory
  trackingId: '<your_tracking_id>', // Mandatory
  debug: true, // Whether or not display console logs debugs (optional)
  vueRouter: router, // Pass the router instance to automatically sync with router (optional)
  ignoredViews: ['homepage'], // If router, you can exclude some routes name (case insensitive) (optional)
  globalDimensions: [ // Optional
    {dimension: 1, value: 'MyDimensionValue'},
    {dimension: 2, value: 'AnotherDimensionValue'}
  ],
  globalMetrics: [ // Optional
      {metric: 1, value: 'MyMetricValue'},
      {metric: 2, value: 'AnotherMetricValue'}
    ]
})
```

How this work on vue-gtm?

**Comment by mib200** [comment]
Hi, apologies for the late reply. Was travelling in past few days.

You include Google GTM normally as you would in any other application. Directly inside index.html (root page) of your app.

For ex: 

`<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-XXXXXX"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-XXXXXX');</script>`

Then in your app.js of Vue project,

`import VueGtm from 'vue-gtm';`
`Vue.use(VueGtm, {`
 ` debug: true, // Whether or not display console logs debugs (optional)`
`  vueRouter: router, // Pass the router instance to automatically sync with router (optional)`
`});`

Simple as that. Updated in ReadMe too.
