### ISSUE TITLE
Passing 'anonymize_ip': true in config is not working

### ISSUE THREAD

**Issue by VictorGa** [mib200/vue-gtm#42]
Hello,

I am trying to set anonymize_ip to true through the main config object, but I can't see the property being set.

```javascript
Vue.use(VueGtm, {
  id: 'XXX', // Your GTM ID
  anonymize_ip: true,
  enabled: true, 
  debug: true,
  vueRouter: router
  ignoredViews: [''] 
});
```

Is there a possibility to pass this property in the config?

Thanks!

**Comment by emptydriptray** [comment]
You can configure this in GTM. https://stackoverflow.com/questions/50528008/how-to-correctly-anonymize-ip-for-tag-manager-code

**Comment by mib200** [comment]
closing this as it can be done in GTM itself
