### ISSUE TITLE
Multiple installations of google tag manager detected

### ISSUE THREAD

**Issue by makeupsomething** [mib200/vue-gtm#47]
When I analyse my site using `Google Tag Assistant` browser extension I get a warning saying 
```
multiple installations of google tag manager detected
```

I am wondering if anyone else has seen this issue? 
I am not sure if it is a problem with `vue-gtm` or with `Google Tag Assistant`

**Comment by dshrestha06** [comment]
We are running into this issue as well. hasScript in utils.js always returns false. document.getElementsByName('script') needs to be changed to document.getElementsByTagName('script')

**Comment by qus1225** [comment]
I am running into this issue, too
