### ISSUE TITLE
Installed npm package missing commit ef89829862f8b595a87f6cae4a8b3f8c1990046c

### ISSUE THREAD

**Issue by Kenvdb** [mib200/vue-gtm#50]
I've installed the plugin with NPM, but commit ef89829862f8b595a87f6cae4a8b3f8c1990046c is missing in my version.

```
trackView(screenName, path) {
    if (inBrowser && pluginConfig.enabled) {
      logDebug('Dispatching TrackView', { screenName, path })

      let dataLayer = (window.dataLayer = window.dataLayer || [])
      dataLayer.push({
        event: 'content-view',
        'content-name': path
      })
    }
  }
```

Also missing some information how to setup GTM would be appreciated.

**Comment by ellefsen** [comment]
+1 having the same issue. I figured you can override existing path and location by creating a separate Content View tag that triggers a GA Page View, and by overriding the settings for the tag you can set fields for location and page with variables from 'content-name' and 'content-view-name'. This can then be triggered by the content-view custom event.

**Comment by Kenvdb** [comment]
@ellefsen thanks for your reply, would be nice to see an example?

What I ended up doing was copying the "src" folder to my local project and added an alias **vue.config.js**

`resolve: {
            alias: {
                'vue-gtm': path.resolve(__dirname, 'resources/js/vue-gtm/')
            }
        }`

I did also tried to build the Vue Gtm with webpack from the project folder, but that resulted in a few build errors: methods/functions where not included in the babel presets (probably stage 2)...

**Comment by mib200** [comment]
v2.1.0 published on NPM with all latest PR's closed
