### ISSUE TITLE
Add multiple google tag manager accounts

### ISSUE THREAD

**Issue by vaishali-ghayal** [mib200/vue-gtm#51]
If it's not implemented yet, this might be a feature request. 
Requirement is adding multiple google tag manager accounts.
If it's implemented already please let me know how to use that.

Thanks in advance!

**Comment by mib200** [comment]
done. you can pass an array now in `id`. Check docs.

**Comment by vaishali-ghayal** [comment]
@mib200 Thank you!

**Comment by jrluiscarvalho** [comment]
Hey @mib200 how are you?

I am having the following problem:

<img width="458" alt="Captura de Tela 2020-03-30 às 08 24 13" src="https://user-images.githubusercontent.com/7990699/77907406-f79de080-725f-11ea-9764-2360f75e8ffb.png">



How do you recommend implementing multiple google tag manager accounts?

Thanks a lot.
