### ISSUE TITLE
set GTM ID dynamically

### ISSUE THREAD

**Issue by liamngth** [mib200/vue-gtm#60]
I am facing a situation where I need to set GTM ID at runtime. I have developed an app which is used for multiple brands (8). Currently, two of them need to apply GTM with different ID. At back-end we will load the ID and set it into vue-gtm
is is possible to achieve that? Please let me know

**Comment by JeremieKaszub** [comment]
I'll be more than glad to have a soltion for this very promblem too. ;Thanks in advance for your time.

**Comment by aniWeyn** [comment]
hi! I also would be glad if changing ID dynamically would be implemented

**Comment by igalgh** [comment]
@liamngth I'm achieving that by postponing the `Vue.use(VueGtm,` until I have the GTM ID.
So, in my case it runs when my app gets a response to an http GET for the dynamic data

**Comment by mib200** [comment]
I use it by making the AJAX call first and then initializing the plugin after the response of the AJAX query.
