### ISSUE TITLE
Can't load gtm.js with url query string dynamically by using config's queryParams object

### ISSUE THREAD

**Issue by NorthBei** [mib200/vue-gtm#62]
I have been opened a pull request for you in #43 ,
Although you close it, because you mereged it manually.
I found the code you mereged manually have some issue about loading gtm.js with different url query string, 
I already leaved detail message in that pull request message list, and give you a reference to solve that issue.

Thank you!

**Comment by Katuva** [comment]
Is this going to be resolved? I need to use query params to pass auth and preview, but obviously not working at all right now.

**Comment by thurst0** [comment]
+1 It looks like the solution is all laid out

**Comment by thurst0** [comment]
Nevermind I think this issue can be closed, looks like it's fixed in #78
