### ISSUE TITLE
The Vue Router tracking includes the slash twice

### ISSUE THREAD

**Issue by WilliamDASILVA** [mib200/vue-gtm#64]
Hello,

It seems that the Vue router tracking includes the slash `/` twice at the beginning of the path. Probably from the baseUrl?
```
VueGtm : Dispatching TrackView {screenName: "Shipments", path: "//shipments/available"}
```

**Comment by luglio7** [comment]
same here

**Comment by shkodasv** [comment]
@WilliamDASILVA  @luglio7  Did you find the solution here? Could it be the reason that the data is not sending to the GTM ?

**Comment by luglio7** [comment]
Nope, i switched to another plugin.

**Comment by shkodasv** [comment]
@luglio7 
thx! Which one? :)

**Comment by luglio7** [comment]
i was wrong, i ended up using google analytics hand coded :)

**Comment by shkodasv** [comment]
thanks!

**Comment by Fifciu** [comment]
My fix for that waits for the review. If someone needs this asap please use my fork.
