### ISSUE TITLE
track pageviews

### ISSUE THREAD

**Issue by rafaelmagalhaes** [mib200/vue-gtm#66]
how can I automatically track every page view for every page with this plugin,
same pages I want to set custom dimensions and that's all working great, but I just noticed pages that don't have events the page views arent working

**Comment by razbakov** [comment]
Page views, history changes, scroll, link clicks are generic events, which is captured by [Google Tag Manager](http://tagmanager.google.com/) automatically. You don't have to code it.

**Comment by simplenotezy** [comment]
Yeah confirmed that's how it is working. I have set up a tag in Google Tag Manager that is the Track Type of "Page View" and then have the trigger to be: All Pages -> Page View and History Change.

![image](https://user-images.githubusercontent.com/3786627/80102470-0cc21280-8573-11ea-855d-ff2742beae56.png)
