### ISSUE TITLE
NPM Update (again ;)

### ISSUE THREAD

**Issue by lgabster** [mib200/vue-gtm#7]
Hi!

Can you update your npm package to the latest git version?
I miss Matthew King's commit, what is add `...rest` attribute.

Thx

**Comment by mib200** [comment]
NPM was updated to 1.0.1 just a few days back. Mathew Kings `...rest` operator was also merged alongside. Did you update the NPM package of your project?

**Comment by lgabster** [comment]
I remove node_modules and reinstall all packages, with this dependency: `"vue-gtm": "^1.0.1"`.
When I opened the `/node_modules/vue-gtm/scr/GtmPlugin.js` file, the ´...rest´ code fregment is missing.

**Comment by lgabster** [comment]
resolved, thx
