### ISSUE TITLE
plugin doesn't track a thing (view)

### ISSUE THREAD

**Issue by marosivanco** [mib200/vue-gtm#70]
When the app is loaded, the initial pageView analytics request:
```
GET https://www.google-analytics.com/r/collect?v=1&_v=j79&a=1885621779&t=pageview&_s=1&...
```
is issued. All the subsequent trackView requests are ignored.

Using vue-gtm@2.2.0
Registration:
```javascript
Vue.use(VueGtm, { id: "GTM-1234567" });
```
Tracking view in the router's afterEach guard:
```javascript
router.afterEach(to => {
	const baseUrl = router.options.base || "";
	Vue.gtm.trackView(to.name, `${baseUrl}${to.fullPath}`);
});
```
If I enable debugging, the console contains log record, for instance:
```
VueGtm : Dispatching TrackView {screenName: "Home", path: "/"}
```
but there is no analytics request in the network tab.

**Comment by igalgh** [comment]
seeing something similar with `trackEvent` called and logging (when debug enabled), but no `collect?=v....` is visible in the network tab and event isn't counted in gtm web panel

**Comment by YannikFirre** [comment]
Same issue any idea ?

**Comment by AriLFrankel** [comment]
same here

**Comment by dylanapplegate** [comment]
It requires a tag and trigger set up within GTM as the plugin only pushes things to the data layer. 

For the event tracking, the best reference I found is: https://www.simoahava.com/analytics/create-a-generic-event-tag/. You'll just need to map the data layer variables a bit different than the article as the data is inserted via:
```
dataLayer.push({
    'event': event || 'interaction',
    'target': category,
    'action': action,
    'target-properties': label,
    'value': value,
    'interaction-type': noninteraction,
    ...rest
});
```
The trigger should look for event name of `interaction`. 

@marosivanco, I haven't dug into the page view side of things, but I imagine something similar would need to be done. 

If I have time, I might open up a PR to update the readme with these tag configurations.

**Comment by irfandyj** [comment]
Is this still an issue?

**Comment by astronati** [comment]
Yes, I'm still having the issue.

**Comment by simplenotezy** [comment]
@jippy89 it's not an issue, it's rather a misunderstanding of how the plugin and google tag manager works. Have a look at my answer here: https://github.com/mib200/vue-gtm/issues/66 - it works perfectly.

**Comment by mib200** [comment]
As @deanbrophy  and @simplenotezy  explained, you need to publish the container in GTM and setup the tracking layer correctly.
