### ISSUE TITLE
queryParams is not working

### ISSUE THREAD

**Issue by Hsueh-Jen** [mib200/vue-gtm#72]
Hi,

I implement my website with different Environment like staging and rc.
I found there is a property call queryParams that I can place gtm_auth, gtm_preview, gtm_cookies_win.

But when I published Google Tag Manager and I check browser with chrome plugin called "Tag Assistant". I saw there is no queryParams append to url.

The Screenshot below is "Tag Assistant" result that implemented with vue-gtm. It is not working.
![](https://i.imgur.com/FYUyrL1.png)

The Screenshot below is "Tag Assistant" result that implemented with copied <script> code from google tag, and it works.
![](https://imgur.com/uWzGf2Z.png)

I already fill in gtm_auth, gtm_preview, gtm_cookies_win in the queryParams just like the official sample code of vue-gtm github page.

Does anyone encountered the same problem? Thanks.

**Comment by AriLFrankel** [comment]
bump @mib200

**Comment by dariusstephen** [comment]
would really appreciate it if you can release this asap

**Comment by honzabilek4** [comment]
Hello @mib200, can we merge the PR #74 related to this? 
This problem makes the library unusable for anything more than just the basic setup.

**Comment by honzabilek4** [comment]
If someone really needs it (as we do), I've published a fixed version here: https://www.npmjs.com/package/@elisiondesign/vue-gtm
Just install the latest version of the package.

**Comment by simplenotezy** [comment]
@mib200 - I guess you must be busy since you created just an awesome package -- amongst other things. I and the other devs here would really appreciate if you could merge this PR - would fix a critical error ;)

**Comment by simplenotezy** [comment]
Hi @honzabilek4 - I have just tried your package (`@elisiondesign/vue-gtm@^2.3.2`) and I can confirm that it is not working. No Query paramteres are added, and I have assigned them acoording to the documentation: 

	Vue.use(VueGtm, {
		id: process.env.GTM_TRACKING_ID,
		queryParams: {
			gtm_auth: '123',
			gtm_preview: 'env-77',
			gtm_cookies_win: 'x'
		},

**Comment by honzabilek4** [comment]
Hello @simplenotezy,
That’s weird. We’re using exactly this version right now and all query parameters work well.
Are you sure you have the package installed correctly? I can investigate it further then.

**Comment by simplenotezy** [comment]
that would be great @honzabilek4 - yes I am sure I have installed the package installed correctly. It is already working on our production site (just without queryParams).

This is how I init gtm:

	Vue.use(VueGtm, {
		id: process.env.GTM_TRACKING_ID, // Your GTM single container ID or array of container ids ['GTM-xxxxxxx', 'GTM-yyyyyyy']
		queryParams: { // Add url query string when load gtm.js with GTM ID (optional)
			gtm_auth: '1234-',
			gtm_preview: 'env-77',
			gtm_cookies_win: 'x'
		},
		enabled: true, // defaults to true. Plugin can be disabled by setting this to false for Ex: enabled: !!GDPR_Cookie (optional)
		debug: true, // Whether or not display console logs debugs (optional)
		loadScript: true, // Whether or not to load the GTM Script (Helpful if you are including GTM manually, but need the dataLayer functionality in your components) (optional)
		vueRouter: app.$router // Pass the router instance to automatically sync with router (optional)
		// ignoredViews: ['homepage'] // If router, you can exclude some routes name (case insensitive) (optional)
	});

Events work fine, but it still does not load queryparams. I have tried re-running my dev server, as well as ensured no other version of vue-gtm is live and available.

How do you set the query params exactly in your config? Then I can compare.

**Comment by honzabilek4** [comment]
I verified the functionality and it just works well.

<img width="476" alt="Screenshot 2020-05-30 at 17 39 34" src="https://user-images.githubusercontent.com/7890555/83332646-ad0b0580-a29c-11ea-96ad-6e0112b1517e.png">
<img width="465" alt="Screenshot 2020-05-30 at 17 39 03" src="https://user-images.githubusercontent.com/7890555/83332649-af6d5f80-a29c-11ea-8396-e41546027445.png">
<img width="609" alt="Screenshot 2020-05-30 at 17 44 16" src="https://user-images.githubusercontent.com/7890555/83332752-34f10f80-a29d-11ea-93db-a737d47a48b1.png">

**Comment by simplenotezy** [comment]
Thanks @mib200 for merging!! ;) It works perfectly now.
