### ISSUE TITLE
Question about "category" and "label"

### ISSUE THREAD

**Issue by matt-e-king** [mib200/vue-gtm#8]
Hey @mib200!

I meant to ask this a while ago... while I was tinkering with adding the `...rest` operator, I noticed that in your `trackEvent()` method that you are  "re-mapping" the `category --> target` and `label --> target-properties` when you `dataLayer.push` them to GTM. 

This occurs here: https://github.com/mib200/vue-gtm/blob/master/src/GtmPlugin.js#L34

If you don't mind me asking why you are doing this? Is there a benefit to the naming convention of "target" and "target-properties"?

I only ask because Google Analytics uses "category" and "label" in their events so I've always found it easier to keep things all the same so it is easier to set up Data Layer Variables.

Thanks!

**Comment by mib200** [comment]
I was creating a generic plugin to be used for other analytics libraries too. So I named it accordingly. Sorry if that created a confusion :)
