### ISSUE TITLE
Adding custom properties to trackEvent in TypeScript

### ISSUE THREAD

**Issue by Katuva** [mib200/vue-gtm#81]
With the latest update, in TypeScript, you can no longer add custom properties to the trackEvent object without TypeScript throwing errors.

This can be resolved by adding the following to the trackEvent type definition:

`[key: string]: any`

Pull request with change: https://github.com/mib200/vue-gtm/pull/80

**Comment by Shinigami92** [comment]
Will add this 👍 

Also I noticed there is a new config value `defer: boolean`

**Comment by Shinigami92** [comment]
Seems like your issue was already fixed with `v2.3.1` https://github.com/mib200/vue-gtm/commit/5ec050fe0a2e810e09fcdc0509d118e68629746b

**Comment by Shinigami92** [comment]
@Katuva Please reopen this if it's not solved for you

**Comment by Abdulrahmanh995** [comment]
@Shinigami92 What about overriding `event` value when syncing with `vue-router`?
Is there any way to achieve this?
