### ISSUE TITLE
`URLSearchParams` does not exist in IE11

### ISSUE THREAD

**Issue by simon-tma** [mib200/vue-gtm#82]
#74 included `URLSearchParams`, without a fallback for browsers (IE11) that don't support it, causing GTM to fail.

**Comment by webmint** [comment]
Have same issue -- app not loading at all at IE11 - error - : 'URLSearchParams' is undefined.

**Comment by webmint** [comment]
I've created PR with fix for this. https://github.com/mib200/vue-gtm/pull/83 @simon-tma you can check fix in my fork
