### ISSUE TITLE
"TypeError: Cannot read property 'defer' of undefined" after enabling the plugin with a user interaction

### ISSUE THREAD

**Issue by peXed** [mib200/vue-gtm#84]
Hello!

If you have the plugin disabled by default and then enable it after a user interaction (confirming the tracking) with `this.$gtm.enable(true)`, you get the error `TypeError: Cannot read property 'defer' of undefined`.

I guess this is caused by the missing config object in GtmPlugin.js line 17.

**Comment by mwicha** [comment]
I found this issue too. Do you found solution to solve this?

**Comment by mwicha** [comment]
@peXed I found vue-gtm version "2.3.0" is work for me.

**Comment by peXed** [comment]
@mwicha unfortunately, this is not working for me. I still get the same error. It seems the queryParams are missing in this call.

**Comment by olzv** [comment]
Facing the same issue. Agree with @peXed that it is caused by missing config parameter:
https://github.com/mib200/vue-gtm/blob/master/src/GtmPlugin.js#L17

**Comment by robgallen** [comment]
Probably caused by #78

**Comment by thbwd** [comment]
I've hotfixed this in a fork: https://github.com/thbwd/vue-gtm/commit/d0f8f89ee662173f72fd532375e5d5e2e1f19111

**Comment by Shinigami92** [comment]
> I've hotfixed this in a fork: [thbwd@d0f8f89](https://github.com/thbwd/vue-gtm/commit/d0f8f89ee662173f72fd532375e5d5e2e1f19111)

Can you also pls open a PR?

**Comment by thbwd** [comment]
@Shinigami92 My fix circumvents the global `pluginConfig`. I don't fully understand the reason for this global object, but this duplication is just an invitation for more bugs in the future. I can refactor the plug-in to remove this global, if you'd like, otherwise my fix doesn't make much sense.

**Comment by Shinigami92** [comment]
Ah ok, let the repo owner decide :)
