### ISSUE TITLE
Changelog and/or Tags

### ISSUE THREAD

**Issue by Shinigami92** [mib200/vue-gtm#92]
Please update your `changelog.md` and/or create tags with some helpful release notes.

**Comment by mib200** [comment]
> Please update your `changelog.md` and/or create tags with some helpful release notes.

I am looking for some maintainers for the repository. Would love some help as I am engaged with some other stuff. Would you like to work on this plugin @Shinigami92 ?

**Comment by Shinigami92** [comment]
Yes, I think I can handle this 👍

https://www.npmjs.com/~shinigami92

**Comment by Shinigami92** [comment]
At first you can add me as a contributor/member of the project with "write" permissions

So over the weekend I can add tags, an updated changelog and rewrite the project to typescript (and then remove use of webpack).
Also I can add GitHub Actions.

**Comment by mib200** [comment]
@Shinigami92 Sent you invites on both NPM & GitHub.

**Comment by Shinigami92** [comment]
Thank you very much

I think I will start in the next few days

**Comment by Shinigami92** [comment]
@mib200 Sorry I'm currently in a process migrating my new setup to an arch linux

I'm new to arch linux and happy to currently have managed to install working plasma 😃

So today or tomorrow a missing cable for my system U.2 SSD arrives and then I have to install everything from scratch...
So will take some more time...

**Comment by mib200** [comment]
> @mib200 Sorry I'm currently in a process migrating my new setup to an arch linux
> 
> I'm new to arch linux and happy to currently have managed to install working plasma 😃
> 
> So today or tomorrow a missing cable for my system U.2 SSD arrives and then I have to install everything from scratch...
> So will take some more time...

No worries friend. Take you time!

**Comment by Shinigami92** [comment]
Tags created

next todos:
1. create releases with messages
2. create changelog (I will use my plugin-pug project as template)

**Comment by Shinigami92** [comment]
releases created

next todo:

1. create changelog (I will use my plugin-pug project as template)

will create a PR for that on weekend (I hope/think :) )

**Comment by Shinigami92** [comment]
Maybe not absolutely accurate, but it does its job
