### ISSUE TITLE
Cannot set property '$gtm' of undefined => Use vue-gtm: 3.0.0-vue2 without ~ or ^

### ISSUE THREAD

**Issue by popovdk** [mib200/vue-gtm#98]
When connecting to an application on Vue 2, an error occurs Uncaught TypeError: Cannot set property '$ gtm' of undefined due to the fact that the plugin is connected via Vue.config.globalProperties, and this is possible only in Vue 3

Installed simply through npm without specifying additional tags

**Comment by Shinigami92** [comment]
Please use the [vue-2](https://www.npmjs.com/package/vue-gtm/v/3.0.0-vue2) version of the plugin

**Comment by Shinigami92** [comment]
@popovdk Please close this issue if this fixed your problem :slightly_smiling_face:

**Comment by bastianaf** [comment]
same issue here. This is my config

`Vue.use(VueGtm, {
	id: 'GTM-SECRET',
	defer: false, 
	enabled: true, 
	debug: true,
	loadScript: true, 
	trackOnNextTick: false, 
  })
`

and got 

![image](https://user-images.githubusercontent.com/22434428/94583306-ab098100-0253-11eb-9d87-deb7506fb445.png)
![image](https://user-images.githubusercontent.com/22434428/94583356-b9579d00-0253-11eb-89a8-86c0440b44a8.png)

**Comment by Shinigami92** [comment]
What do you have in your `package.json`?

Please try 

```json
{
  ...
  "dependencies": {
    ...
    "vue-gtm": "3.0.0-vue2"
  }
}
```

without `~` or `^`
Then remove `node_modules` and reinstall

If you are using `~` or `^` and not the exact version you may fallback to the `latest` version, and this is the vue 3 branch :warning: 

---

I can confirm that [3.0.0-vue2](https://www.npmjs.com/package/vue-gtm/v/3.0.0-vue2) is really the [vue2](https://github.com/mib200/vue-gtm/tree/vue-2) branch: https://unpkg.com/vue-gtm@3.0.0-vue2/dist/index.js

**Comment by bastian-af** [comment]
thats work

> What do you have in your `package.json`?
> 
> Please try
> 
> ```json
> {
>   ...
>   "dependencies": {
>     ...
>     "vue-gtm": "3.0.0-vue2"
>   }
> }
> ```
> 
> without `~` or `^`
> Then remove `node_modules` and reinstall
> 
> If you are using `~` or `^` and not the exact version you may fallback to the `latest` version, and this is the vue 3 branch ⚠️
> 
> I can confirm that [3.0.0-vue2](https://www.npmjs.com/package/vue-gtm/v/3.0.0-vue2) is really the [vue2](https://github.com/mib200/vue-gtm/tree/vue-2) branch: https://unpkg.com/vue-gtm@3.0.0-vue2/dist/index.js

this work for me, thanks a lot

**Comment by bastianaf** [comment]
> What do you have in your `package.json`?
> 
> Please try
> 
> ```json
> {
>   ...
>   "dependencies": {
>     ...
>     "vue-gtm": "3.0.0-vue2"
>   }
> }
> ```
> 
> without `~` or `^`
> Then remove `node_modules` and reinstall
> 
> If you are using `~` or `^` and not the exact version you may fallback to the `latest` version, and this is the vue 3 branch ⚠️
> 
> I can confirm that [3.0.0-vue2](https://www.npmjs.com/package/vue-gtm/v/3.0.0-vue2) is really the [vue2](https://github.com/mib200/vue-gtm/tree/vue-2) branch: https://unpkg.com/vue-gtm@3.0.0-vue2/dist/index.js

this works for me, thanks a lot

**Comment by mbence** [comment]
Sorry guys, I'm a little confused:
https://github.com/mib200/vue-gtm/compare/3.0.0-vue2...3.0.0

Anyway, I still get `main.js?56d7:50 Uncaught TypeError: vue_gtm__WEBPACK_IMPORTED_MODULE_18___default(...) is not a function` with Vue 2 and
```
    "vue-gtm": "3.0.0-vue2",
```

**Comment by Shinigami92** [comment]
- `3.0.0` is for vue 3
- `3.0.0-vue2` is for vue 2

also please clear your node_modules and perform npm or yarn install again

**Comment by wagslane** [comment]
Can the requirement `3.0.0-vue2` be added to the docs?

**Comment by Shinigami92** [comment]
Sure, if you want you can open a PR :)
If not, I think I will add it tomorrow or so

**Comment by Shinigami92** [comment]
@lane-c-wagner Added https://github.com/mib200/vue-gtm/commit/6f1577458199387d8dce9a3c6e4cae1aded318f9

**Comment by AndrewBogdanovTSS** [comment]
Is there any way to protect a use of `^` for `-vue2` version? Right now it's very confusing behavior

**Comment by Shinigami92** [comment]
If you know a strategy, please let me know!
I'm not well into npm publishing

**Comment by AndrewBogdanovTSS** [comment]
@Shinigami92 you need to create 2 different packages for each project, that's the most common-sense solution. Plus your issues for different Vue versions won't mix up and it will all look more organized this way. I guess you can even use a package namespace, something similar to vue or nuxt is doing. e.g. `@vue-gtm/vue-2` `@vue-gtm/vue-3`

**Comment by Shinigami92** [comment]
For doing so, I need permission by the license owner @mib200 
This is not my repo. If he give me permission to transfer everything to me or create an organization structure (in npm and github) and provide admin access, I can do it.

Currently I even don't have permission to protect the `vue-2` branch ^^'

**Comment by cartok** [comment]
Can this be solved in a more generic way, so you would not need that additional layer?

**Comment by cartok** [comment]
What do you think about checking the vue version and depending on the result **import()** the code you need guys?

**Comment by Shinigami92** [comment]
Without breaking TypeScript support? I don't think so.

If you have time to experiment with it, creating compatibility for Vue 2 and Vue 3 together, feel free to do so :slightly_smiling_face: 

But in the (very) long-term this is irrelevant, as support for Vue 2 will one day be discontinued

**Comment by antoci-alin** [comment]
I'm also interested in a cleaner approach for this versioning.

**Comment by KhozmoS** [comment]
Hi guys, why dont put on the README.MD this **important** info:
_Cannot set property '$gtm' of undefined => Use vue-gtm: 3.0.0-vue2 without ~ or ^
#98_

**Comment by Shinigami92** [comment]
@KhozmoS ... it is on the readme...
<img src="https://user-images.githubusercontent.com/7195563/102631569-2e998680-414e-11eb-9550-8b43d00fddc8.jpeg" width="300px"/>

Oh, and beside that it's already there: this is an Open Source project, so you can create PRs for it, also for `README.md`
So if you miss anything, feel free and I will make a review and merge it

**Comment by KhozmoS** [comment]
@Shinigami92 really don't know how I didn't see that... my bad 👌

**Comment by Shinigami92** [comment]
We could try https://github.com/vueuse/vue-demi :thinking:
