### ISSUE TITLE
GTM_ID_PATTERN to support IDs like G-XXXXXXXXXX

### ISSUE THREAD

**Issue by antongorodezkiy** [mib200/vue-gtm#99]
## Request / Idea

Today got from the client the tag manager ID with pattern G-XXXXXXXXXX. `vue-gtm` thrown a validation exception when I tried to use it (of course). Maybe we should pass ID as is and let user and google validate it?

## Additional Context

...

**Comment by antongorodezkiy** [comment]
Never mind, that was my mistake, that ID is for https://www.googletagmanager.com/gtag, not for https://www.googletagmanager.com/gtm

**Comment by Shinigami92** [comment]
Now I'm glad I implemented this pattern 😛

But thanks for using this plugin :slightly_smiling_face:
